### ISSUE TITLE
build & install clippy problem

### ISSUE THREAD

**Issue by bmullan** [bketelsen/clippy#1]
I thought I'd try to build clippy and see what it does...

**$ go version
go version go1.11.5 linux/amd64**

Clone repo - ok,   cloned into **~/Downloads/clippy** 

**go get -u github.com/gobuffalo/packr/v2/packr2** - ok

**packr2 build** -fails with

~/Downloads/clippy$ packr2 build ./packr2/packed-packr.go
stat ./packr2/packed-packr.go: no such file or directory
Error: exit status 1
Usage:
  packr2 build [flags]

Flags:
  -h, --help   help for build

Global Flags:
      --ignore-imports     when set to true packr won't resolve imports for boxes
      --legacy             uses the legacy resolution and packing system (assumes first arg || pwd for input path)
      --silent             silences all output
      --store-cmd string   sub command to use for packing
  -v, --verbose            enables verbose logging

solution seems to be to change into the ./packrd directory then execute 

~/Downloads/clippy/packrd/**packr2 build** -- returns to prompt w/no error msgs

but ... not sure if it did or didn't build ... it was very quick

~/Downloads/clippy/packrd/**packr2 install** -- returns to prompt w/no error msgs

but ... not sure if it installed anything as I couldn't

$ sudo find / -name clippy

returns nothing but the ~/Downloads/clippy directory name and no executable anywhere else ?

Are there some steps missing or am I not doing this correctly?

thanks
brian

**Comment by bketelsen** [comment]
hmm, maybe a dependency is broken. I'll try to get this fixed!
